name: pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read      # Allows reading the repo
  pages: write        # Allows writing to gh-pages
  id-token: write     # Required for OpenID Connect (needed by deploy-pages)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16  # or 18, etc., matching your project’s needs

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build project
        run: |
          cd frontend
          # "predeploy" should output your static site into ./frontend/out
          npm run predeploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # IMPORTANT: Only upload your built frontend folder,
          # not the entire repo.
          path: ./frontend/out

  deploy:
    # This job depends on the build job
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write  # needed by actions/deploy-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages
